version: "3.9"

services:
  web:
    build:
      context: .
    command: ["gunicorn", "core.wsgi:application", "-b", "0.0.0.0:8000"]
    container_name: social-application
    restart: always
    environment:
          - "DB_HOST=db"
          - "REDIS_HOST=redis"
    ports:
      - "8000:8000"
    volumes:
      - .:/src
      - static_files:/var/www/social
    env_file:
      - ./.env
    depends_on:
      - db

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - /home/pooya/docker/data:/var/lib/postgresql/data/
    container_name: social-postgres
    restart: always
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
      - "POSTGRES_DB=social"
      - "POSTGRES_USER=test"
      - "POSTGRES_PASSWORD=test"
  redis:
      image: redis:7.2.0
      container_name: social-redis
      restart: always
  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    container_name: social-nginx
    restart: always
    ports:
      - "1337:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - static_files:/var/www/social
    depends_on:
      - web

volumes:
  postgres_data:
  static_files:
