version: "3.9"

services:
  web:
    build: .
    command: ["gunicorn", "core.wsgi:application", "-b", "0.0.0.0:8000"]
    container_name: social-django
    restart: always
    environment:
          - "DB_HOST=db"
    volumes:
      - .:/src
    depends_on:
      - db

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    container_name: social-postgres
    restart: always
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
      - "POSTGRES_DB=social"
      - "POSTGRES_USER=test"
      - "POSTGRES_PASSWORD=test"

  nginx:
#    build: ./nginx
    image: nginx:1.25
    container_name: social-nginx
    restart: always
    ports:
      - "1337:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/social_django.conf:ro
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
  media_volume: