# Generated by Django 4.1.7 on 2023-03-28 10:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_post_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='creataed',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
