# Generated by Django 4.1.7 on 2023-03-30 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_rename_creataed_comment_created_alter_comment_text'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
